@startuml
class logic.controller.GameController {
}
interface logic.explosion.ExplosionStrategy {
~ void explode(Board,int,int,Set<Point>)
}

class logic.utils.CandyMixer {
+ {static} ExplosionStrategy getComboExplosion(Candy,Candy)
+ {static} boolean isStriped(CandyType)
}

enum logic.controller.GameState {
}
class logic.utils.MatchProcessor {
+ {static} Set<Point> processMatches(List<Set<Candy>>,Candy)
}

class logic.explosion.LineExplosion {
- boolean isVertical
- int blastRadius
+ void explode(Board,int,int,Set<Point>)
}


class logic.explosion.ColorBombExplosion {
- CandyColor targetColor
+ void setTargetColor(CandyColor)
+ void explode(Board,int,int,Set<Point>)
- CandyColor randomColor()
}


class logic.board.BoardUpdater {
}
class logic.board.Board {
- int rows
- int cols
- Candy[][] grid
+ boolean isValid(int,int)
+ Candy getCandy(int,int)
+ void setCandy(int,int,Candy)
+ int getRows()
+ int getCols()
+ Candy[][] getGrid()
}


enum logic.candy.CandyColor {
+  RED
+  GREEN
+  YELLOW
+  PURPLE
+  BLUE
+  NONE
}

class logic.explosion.CrossExplosion {
+ void explode(Board,int,int,Set<Point>)
}

abstract class logic.explosion.ExplosionBase {
+ void addAndTrigger(Board,int,int,Set<Point>)
}

class logic.explosion.AreaExplosion {
- int radius
+ void explode(Board,int,int,Set<Point>)
}


enum logic.candy.CandyType {
+  NORMAL
+  STRIPED_HOR
+  STRIPED_VER
+  BOMB
+  COLOR_BOMB
}

class logic.candy.Candy {
- int r
- int c
- boolean isRemove
- CandyColor color
- CandyType type
- ExplosionStrategy explosion
+ void setRow(int)
+ void setColumn(int)
+ void setIsRemove(boolean)
+ void setType(CandyType)
+ void performExplosion(Board,Set<Point>)
+ void prepareColorBomb(CandyColor)
+ int getRow()
+ int getColumn()
+ boolean isRemove()
+ CandyType getType()
+ CandyColor getColor()
}


class logic.explosion.ColorBombBombExplosion {
- CandyColor targetColor
+ void setTargetColor(CandyColor)
+ void explode(Board,int,int,Set<Point>)
}


class logic.board.BoardPhysics {
}
class logic.explosion.NukeExplosion {
+ void explode(Board,int,int,Set<Point>)
}

class logic.utils.SpecialCandyRules {
+ {static} CandyType analyzeShape(Set<Candy>)
}

class logic.explosion.NormalExplosion {
+ void explode(Board,int,int,Set<Point>)
}

class logic.explosion.ColorStripedExplosion {
- CandyColor targetColor
- Random random
+ void setTargetColor(CandyColor)
+ void explode(Board,int,int,Set<Point>)
}


class logic.utils.Point {
+ int r
+ int c
+ boolean equals(Object)
+ int hashCode()
}


class logic.utils.MatchFinder {
~ Board board
+ List<Set<Candy>> findMatchAt(int,int)
+ List<Set<Candy>> findAllMatches()
+ List<Set<Candy>> mergeClusters(List<Set<Candy>>)
+ boolean checkColor(int,int,CandyColor)
+ boolean shouldEndRun(List<Candy>,Candy)
}




logic.explosion.ExplosionBase <|-- logic.explosion.LineExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.ColorBombExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.CrossExplosion
logic.explosion.ExplosionStrategy <|.. logic.explosion.ExplosionBase
logic.explosion.ExplosionBase <|-- logic.explosion.AreaExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.ColorBombBombExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.NukeExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.NormalExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.ColorStripedExplosion
@enduml