@startuml
class logic.board.BoardInitializer {
- {static} Random random
+ {static} void initialize(Board,MatchFinder,GameMode)
- {static} void fillBoardNoInitialMatches(Board,GameMode)
+ {static} boolean isCreatingMatch(Board,int,int,CandyColor)
- {static} CandyColor getRandomColor()
}


class gui.components.ItemPane {
- String itemType
- int count
- GameController controller
- Button button
- Consumer<Set<Point>> onActionSuccess
- Supplier<Boolean> canClick
- void handleItemClick()
- boolean isInstantItem()
- Item createItemStrategy()
+ void refreshCount()
+ void updateState()
+ void updateButtonText(String)
- void styleButton(String)
}


class logic.explosion.LineExplosion {
- boolean isVertical
- int blastRadius
+ void explode(Board,int,int,Set<Point>)
}


class gui.components.BoardPane {
+ void update(Board,Set<Point>,int,int,BiConsumer<Integer,Integer>)
}

class logic.explosion.ColorBombExplosion {
- CandyColor targetColor
+ void setTargetColor(CandyColor)
+ void explode(Board,int,int,Set<Point>)
- CandyColor randomColor()
}


class logic.board.BoardUpdater {
- {static} Random random
+ {static} void updateBoard(Board,Set<Point>)
- {static} void refillBoard(Board)
- {static} Candy generateRandomCandy(Board,int,int)
+ {static} void shuffleBoard(Board)
- {static} void applyGravity(Board)
- {static} void applyGravityColumn(Board,int,int)
}


class application.Main {
+ void start(Stage)
+ {static} void main(String[])
}

interface gui.base.View {
~ Scene getScene()
}

class logic.explosion.CrossExplosion {
+ void explode(Board,int,int,Set<Point>)
}

class logic.candy.Candy {
- int r
- int c
- boolean isRemove
- CandyColor color
- CandyType type
- ExplosionStrategy explosion
- boolean isFrozen
- boolean isJustMelt
+ void setRow(int)
+ void setColumn(int)
+ void setIsRemove(boolean)
+ void setType(CandyType)
+ void performExplosion(Board,Set<Point>)
+ void prepareColorBomb(CandyColor)
+ int getRow()
+ int getColumn()
+ boolean isRemove()
+ CandyType getType()
+ CandyColor getColor()
+ void setColor(CandyColor)
+ boolean isFrozen()
+ void setFrozen(boolean)
+ boolean isJustMelt()
+ void setJustMelt(boolean)
}


class logic.explosion.ColorBombBombExplosion {
- CandyColor targetColor
+ void setTargetColor(CandyColor)
+ void explode(Board,int,int,Set<Point>)
}


class logic.explosion.NukeExplosion {
+ void explode(Board,int,int,Set<Point>)
}

class logic.Item.BombItem {
- {static} int amount
+ List<Point> use(Board,GameMode)
}


class gui.components.AnimatedBackground {
- Pane pane
- Random random
- Color[] colors
+ Pane getPane()
- void createFloatingCandy()
- void animateCandy(Circle)
}


class logic.Item.IceBreakItem {
+ List<Point> use(Board,GameMode)
}

abstract class logic.Item.Item {
# Random random
+ {abstract}List<Point> use(Board,GameMode)
# List<Candy> getRandomCandy(Board,int)
}


class logic.controller.GameController {
- Board board
- MatchFinder matchFinder
- GameState gameState
- GameMode gameMode
- int score
- int moveLeft
- Random random
- int bombItemAmount
- int iceItemAmount
- int stripedItemAmount
+ void initializeGame()
+ Set<Point> handleSwap(int,int,int,int)
- void performSwap(int,int,int,int)
+ void boardUpdate(Set<Point>)
+ Set<Point> checkChainReaction()
+ void endTurn()
+ List<Point> applyItemTransform(Item)
+ Set<Point> activateItems(List<Point>)
+ void setMoveLeft(int)
+ int getMoveLeft()
+ Board getBoard()
+ GameState getGameState()
+ int getScore()
+ GameMode getGameMode()
+ void setReadyToPlay()
+ int getBombItemAmount()
+ int getIceItemAmount()
+ int getStripedItemAmount()
}


interface logic.explosion.ExplosionStrategy {
~ void explode(Board,int,int,Set<Point>)
}

class gui.views.EndView {
- Scene scene
+ Scene getScene()
- void styleButton(Button,String)
}


class logic.utils.CandyMixer {
+ {static} ExplosionStrategy getComboExplosion(Candy,Candy)
- {static} boolean isStriped(CandyType)
}

class gui.components.ControlPane {
- ItemPane item1
- ItemPane item2
- ItemPane item3
- GameController controller
+ void resetCounts()
}


enum logic.controller.GameState {
+  PLAY
+  PROCESS
+  GAME_OVER
}

enum logic.controller.GameMode {
+  NORMAL
+  HARD
}

class gui.base.ViewManager {
- {static} ViewManager instance
- Stage mainStage
+ {static} ViewManager getInstance()
+ void setMainStage(Stage)
+ void showStartScreen()
+ void showGameScreen(GameMode)
+ void showEndScreen(int)
}


class logic.utils.MatchProcessor {
+ {static} Set<Point> processMatches(Board,List<Set<Candy>>,Candy)
}

class gui.views.StartView {
- Scene scene
- void styleButton(Button,String)
+ Scene getScene()
}


class gui.components.CandyTile {
- {static} int TILE_SIZE
- void drawCandyImage(Candy)
- String getImagePath(Candy)
}


class gui.base.SoundManager {
- {static} MediaPlayer bgmPlayer
+ {static} void playBGM(String)
+ {static} void stopBGM()
+ {static} void playSFX(String)
}


class logic.board.Board {
- int rows
- int cols
- Candy[][] grid
+ boolean isValid(int,int)
+ Candy getCandy(int,int)
+ void setCandy(int,int,Candy)
+ int getRows()
+ int getCols()
+ Candy[][] getGrid()
}


enum logic.candy.CandyColor {
+  RED
+  GREEN
+  YELLOW
+  PURPLE
+  BLUE
+  NONE
}

class logic.explosion.AreaExplosion {
- int radius
+ void explode(Board,int,int,Set<Point>)
}


abstract class logic.explosion.ExplosionBase {
+ void addAndTrigger(Board,int,int,Set<Point>)
}

enum logic.candy.CandyType {
+  NORMAL
+  STRIPED_HOR
+  STRIPED_VER
+  BOMB
+  COLOR_BOMB
}

class gui.views.GameView {
- {static} int ROWS
- {static} int COLS
- Scene scene
- GameController controller
- BoardPane boardPane
- ControlPane controlPane
- Label scoreLabel
- Label moveLabel
- boolean isAnimating
- int selectedRow
- int selectedCol
- void styleLabel(Label)
+ Scene getScene()
- void updateView(Set<Point>)
- void handleTileClick(int,int)
- void runGameLoop(Set<Point>)
- void checkGameOver()
}


class logic.Item.StripedItem {
+ List<Point> use(Board,GameMode)
}

class logic.explosion.NormalExplosion {
+ void explode(Board,int,int,Set<Point>)
}

class logic.utils.SpecialCandyRules {
+ {static} CandyType analyzeShape(Set<Candy>)
}

class logic.explosion.ColorStripedExplosion {
- CandyColor targetColor
- Random random
+ void setTargetColor(CandyColor)
+ void explode(Board,int,int,Set<Point>)
}


class logic.utils.Point {
+ int r
+ int c
+ boolean equals(Object)
+ int hashCode()
}


class logic.utils.MatchFinder {
~ Board board
+ List<Set<Candy>> findMatchAt(int,int)
+ List<Set<Candy>> findAllMatches()
+ List<Set<Candy>> mergeClusters(List<Set<Candy>>)
+ boolean checkColor(int,int,CandyColor)
+ boolean shouldEndRun(List<Candy>,Candy)
+ boolean hasPotentialMatch()
- boolean checkVirtualSwap(int,int,int,int)
}




javafx.scene.layout.StackPane <|-- gui.components.ItemPane
logic.explosion.ExplosionBase <|-- logic.explosion.LineExplosion
javafx.scene.layout.GridPane <|-- gui.components.BoardPane
logic.explosion.ExplosionBase <|-- logic.explosion.ColorBombExplosion
javafx.application.Application <|-- application.Main
logic.explosion.ExplosionBase <|-- logic.explosion.CrossExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.ColorBombBombExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.NukeExplosion
logic.Item.Item <|-- logic.Item.BombItem
logic.Item.Item <|-- logic.Item.IceBreakItem
gui.base.View <|.. gui.views.EndView
javafx.scene.layout.HBox <|-- gui.components.ControlPane
gui.base.View <|.. gui.views.StartView
javafx.scene.layout.StackPane <|-- gui.components.CandyTile
logic.explosion.ExplosionBase <|-- logic.explosion.AreaExplosion
logic.explosion.ExplosionStrategy <|.. logic.explosion.ExplosionBase
gui.base.View <|.. gui.views.GameView
logic.Item.Item <|-- logic.Item.StripedItem
logic.explosion.ExplosionBase <|-- logic.explosion.NormalExplosion
logic.explosion.ExplosionBase <|-- logic.explosion.ColorStripedExplosion
@enduml